export const Colors = {
  primary: '#0058be',
  onPrimary: '#ffffff',
  primaryContainer: '#2170e4',
  onPrimaryContainer: '#fefcff',
  primaryFixed: '#d8e2ff',
  primaryFixedDim: '#adc6ff',
  onPrimaryFixed: '#001a42',
  onPrimaryFixedVariant: '#004395',
  inversePrimary: '#adc6ff',

  secondary: '#505f76',
  onSecondary: '#ffffff',
  secondaryContainer: '#d0e1fb',
  onSecondaryContainer: '#54647a',
  secondaryFixed: '#d3e4fe',
  secondaryFixedDim: '#b7c8e1',
  onSecondaryFixed: '#0b1c30',
  onSecondaryFixedVariant: '#38485d',

  tertiary: '#595c5e',
  onTertiary: '#ffffff',
  tertiaryContainer: '#727577',
  onTertiaryContainer: '#fbfdff',
  tertiaryFixed: '#e0e3e5',
  tertiaryFixedDim: '#c4c7c9',
  onTertiaryFixed: '#191c1e',
  onTertiaryFixedVariant: '#444749',

  error: '#ba1a1a',
  onError: '#ffffff',
  errorContainer: '#ffdad6',
  onErrorContainer: '#93000a',

  background: '#faf8ff',
  onBackground: '#131b2e',

  surface: '#faf8ff',
  surfaceDim: '#d2d9f4',
  surfaceBright: '#faf8ff',
  surfaceContainerLowest: '#ffffff',
  surfaceContainerLow: '#f2f3ff',
  surfaceContainer: '#eaedff',
  surfaceContainerHigh: '#e2e7ff',
  surfaceContainerHighest: '#dae2fd',
  surfaceVariant: '#dae2fd',
  surfaceTint: '#005ac2',
  onSurface: '#131b2e',
  onSurfaceVariant: '#424754',

  inverseSurface: '#283044',
  inverseOnSurface: '#eef0ff',

  outline: '#727785',
  outlineVariant: '#c2c6d6',
} as const;
